PPW/urls.py
from django.contrib import admin
from django.urls import path, include

from PPW import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab_1/', include('lab_1.urls')),
    path('lab_4/',include('lab_4.urls')),
    path('lab_5/',include('lab_5.urls')),
    path('',views.lab_5)
]

lab_1/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index)
]

lab_4/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index),
    path('not_found/',views.not_found),
    path('experience/',views.experience)
]

lab_5/urls.py
from django.urls import path

from . import views

app_name="lab5"

urlpatterns=[
    path("", views.index, name="index" ),
    path("delete/<int:id>", views.delete_schedule, name="delete_schedule")
]

lab_1/models.py
from django.db import models

# Create your models here.

lab_4/models.py
from django.db import models

# Create your models here.

lab_5/models.py
from django.db import models

# Create your models here.
class Schedule(models.Model):
    title = models.CharField(max_length=100)
    location = models.CharField(max_length=200)
    categories = models.CharField(max_length=100)
    date = models.DateField(null=True)
    time = models.TimeField(null=True)
    day = models.CharField(max_length=100)

PPW/views.py
from django.shortcuts import redirect


def lab_1(request):
    return redirect('/lab_1/')

def lab_4(request):
    return redirect('/lab_4/')

def lab_5(request):
    return redirect('/lab_5/')

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
# Enter your name here
mhs_name = 'Dipta Laksmana Baswara' # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(2000,3,9) #TODO Implement this, format (Year, Month, Date)
npm = 1806235832 # TODO Implement this
# Create your views here.
def index(request):
    response = {'name': mhs_name, 'age': calculate_age(birth_date.year), 'npm': npm}
    return render(request, 'index_lab1.html', response)

def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

lab_4/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'lab_4/profile.html');

def not_found(request):
    return render(request, 'lab_4/notfound.html')

def experience(request):
    return render(request, 'lab_4/experience.html')

lab_5/views.py
import datetime

from django.shortcuts import render, redirect
from . import form,models
# Create your views here.
def index(request):
    if(request.method == "POST"):
            forms = form.ScheduleForm(request.POST);
            if(forms.is_valid()):
                schedule = models.Schedule(title=request.POST['title'],
                                           location=request.POST['location'],
                                           date="{}-{:02d}-{:02d}".format(request.POST['date_year'],int(request.POST['date_month']),int(request.POST['date_day'])),
                                           categories=request.POST['categories'],
                                           time=request.POST['time'],
                                           day=request.POST['day']
                                           )
                schedule.save()
                return redirect('/lab_5')
            else:
                list_schedule = models.Schedule.objects.all().order_by('date').order_by('time')
                return render(request, 'lab_5/schedule.html', {'forms':forms, 'schedules':list_schedule, "length":len(list_schedule)})
    else:
        forms = form.ScheduleForm()
        list_schedule = models.Schedule.objects.all().order_by('date').order_by('time')
        return render(request, 'lab_5/schedule.html', {'forms':forms, 'schedules':list_schedule, "length":len(list_schedule)})

def delete_schedule(request,id):
    if(request.method == "POST"):
        schedule = models.Schedule.objects.get(id=id)
        schedule.delete()
        return redirect('/lab_5')

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ name }}</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/static/lab_1.css">
</head>
<body>
    <div class="section1">
        <img src="/static/_MG_3231_ 3x4.jpg" class="profile-img" />
        <div class="desc">
            <h1>Hello my name is <br>  {{ name }}</h1>
            <p>NPM : {{ npm }}</p>
            <p>I am {{ age }} years old</p>
            <p>Generation : <a href="https://quanta2018.com/" class="quanta">Quanta (2018)</a></p>
            <p>University : Universitas Indonesia</p>
            <p>My Hobby is : Coding, Playing Competitive Game, and Travelling</p>
            <p style="overflow-wrap: break-word; max-width: 500px;">Description : <br> I am a person who like computer very much, hard worker, very interesting in technology (whatever it is)</p>
        </div>
    </div>
</body>
</html>

lab_4/templates/lab_4/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/Lab_3/profile2.css">
    <title>Welcome To My Website</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light" id="navbar">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse navbar-menu" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="/lab_4#about" class="" id="about-a">About</a>
                </li>
                <li class="nav-item">
                    <a href="/lab_4#education" class="" id="education-a" >Education</a>
                </li>
                <li class="nav-item">
                    <a href="/lab_4/experience#experience" class=""  id="experience-a" >Experience</a>
                </li>
                <li class="nav-item">
                    <a href="/lab_4/experience#project" class="" id="project-a">Project</a>
                </li>
                <li class="nav-item">
                    <a href="/lab_4/experience#achievement" class=""  id="achievement-a">Achievement</a>
                </li>
                <li class="nav-item">
                    <a href="/lab_4/experience#skills" class=""  id="skills-a">Skills</a>
                </li>
                <li class="nav-item">
                    <a href="/lab_4#contact" class="" id="contact-a">Contact</a>
                </li>
                <li class="nav-item">
                    <a href="/lab_5#schedule" class="" id="schedule-a">Schedule</a>
                </li>
            </ul>
        </div>
    </nav>
    <div>
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="/static/Lab_3/ScrollWatch.js"></script>
    <script src="/static/Lab_3/SmoothScroll.js"></script>
    <script src="/static/Lab_3/main.js"></script>
    <script src="/static/Lab_3/project.js"></script>
    <script src="/static/Lab_3/skills.js"></script>
</body>
</html>

lab_4/templates/lab_4/experience.html
{% extends 'lab_4/base.html' %}

{% block content %}
    <div id="experience" class="container part" style="margin-top: 0px; padding-top: 5rem;" >
        <h1 class="title" id="experience-title">Experience</h1>
        <h4 class="subtitle" id="experience-subtitle">I've been involved here</h4>
        <div class="row justify-content-center content" style="margin-top: 3.5rem;">
            <div class="col-md-5 mx-auto">
                <div class="row">
                    <img src="/static/logo-bem.png" alt="" class="img-fluid align-self-center" >
                    <div class="col-md">
                        <h3 style="font-weight: bold">BEM Fasilkom UI</h3>
                        <h5>Staff at <span style="color: #46413B; font-weight: bold">Media Bureau</span></h5>
                        <h6>2019 - 2020</h6>
                    </div>
                </div>
                <div class="col mt-4">
                    <p class="text-justify">Description : <br>In here, i act as media partner of community service department, the task of media partner here is to make an infographics for social media. Beside that i also hold the iMaba project. iMaba is a web that provide an information about lectures in University of Indonesia for new student in Computer Science in University of Indonesia.</p>
                </div>
            </div>
            <div class="col-md-5 mx-auto">
                <div class="row">
                    <img class="img-fluid align-self-center" src="/static/Compfest.svg" alt="" style="margin-right: 2rem">
                    <div class="col-md">
                        <h3 style="font-weight: bold">COMPFEST</h3>
                        <h5>Participant at <span style="color: #46413B; font-weight: bold">Software Engineering Academy</span></h5>
                        <h6>2019</h6>
                    </div>
                </div>
                <div class="col mt-4">
                    <p class="text-justify">Description : <br>In here, i act as media partner of community service department, the task of media partner here is to make an infographics for social media. Beside that i also hold the iMaba project. iMaba is a web that provide an information about lectures in University of Indonesia for new student in Computer Science in University of Indonesia.</p>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="container part" id="project">
                <h1 class="title" id="project-title">Project</h1>
                <h4 class="subtitle" id="project-subtitle">This is my masterpiece...</h4>
            <div class="row mt-4" id="project-content">
                            <!-- code injected project.js -->
            </div>
        </div>
    </div>
    <hr>
    <div class="container part" id="achievement">
        <div class="row">
            <div class="col-sm-4 align-self-center">
                <h1 class="title" id="achievement-title">Achievement</h1>
                <h4 class="subtitle" id="achievement-subtitle">Something that i got</h4>
            </div>
            <div class="col achievement-card-1 my-3">
                <div>
                    <h3 class="bold">Best Participant</h3>
                    <h5>at <span class="semibold">Software Engineering Academy</span></h5>
                    <h6>2019</h6>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="container part" id="skills">
        <div class="row justify-content-center">
            <div class="col align-self-center">
                <h1 class="title" id="skills-title">Skills</h1>
                <h4 class="subtitle" id="skills-subtitle">I can use this things</h4>
            </div>
            <div class="col-9 align-self-center" id="skill-wrapper">
                <div id="skill-lists"></div>
            </div>
        </div>
    </div>
{% endblock %}

lab_4/templates/lab_4/notfound.html
{% extends "lab_4/base.html" %}

{% block content %}
    <div class="container-fluid">
        <div class="row align-content-center justify-content-center"  style="height: 100vh;">
            <div class="col-4 align-self-center">
                <img src="/static/undraw_page_not_found_su7k.svg" alt="" class="img-fluid mb-5 text-center">
                <h3 class="text-center">Still in construction</h3>
            </div>   
        </div>
    </div>
{% endblock %}

lab_4/templates/lab_4/profile.html
{% extends 'lab_4/base.html' %}

{% block content %}
    <div class="landing-page container-fluid" id="home">
            <div class="row justify-content-center" style="height: 100%;">
                    <img class="img-fluid" id="home-img" src="/static/Foto.png" alt="">
                    <div class="greetings align-self-center col">
                        <h1 >Hello, I'm <span>Dipta</span></h1>
                        <h3 >I'm a Developer</h3>
                        <br>
                        <h2 style="color: #22232A;">Want to Know Me?</h2>
                        <h2 style="color: #46413B;">Keep Scrolling</h2>
                    </div>
            </div>
    </div>
    <div class="container part" id="about">
        <div class="row" >
            <div class="col-md-4 align-self-center">
                <h1 class="title" id="about-title">About</h1>
                <h4 class="subtitle" id="about-subtitle">A brief story about me</h4>
            </div>
            <div class="col-md-8 align-self-center content">
                <p class="text-justify">My Name is Dipta Laksmana Baswara, I’m a person who has high interest in computer. I like anything about computer, from software to hardware.</p>
                <p class="text-justify">I’ve learned programming since high school from an extracurricular. I like programming because it’s fun ,it can create anything i like, and it can be useful in the future. </p>
                <p class="text-justify">Beside programming i learn design too, using Photoshop, Illustrator, and Figma.
                    </p>
            </div>
        </div>
    </div>
    <hr>
    <div class="container part" id="education">
        <div class="row">
            <div class="col-md-5 align-self-center">
                <h1 class="title" id="education-title">Education</h1>
                <h4 class="subtitle" id="education-subtitle">Where have I studied?</h4>
            </div>
            <div class="col-md align-self-center edu-detail-wrapper">
                <a href="https://www.ui.ac.id/" class="no-style edu-detail text-center" target="_blank">
                    <img src="/static/Logo Makara.svg" class="img-fluid mb-3" alt="">
                    <div class="edu-detail-text text-left">
                        <h4>University Of Indonesia</h3>
                        <h5>2018 - Present</h5>
                        <br>
                        <h5>Bachelor Of</h5>
                        <h4>Computer Science</h4>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <hr>
    <div class="container part" id="contact">
        <div class="justify-content-start" style="display: flex; flex-direction: row; flex-wrap: wrap;"> 
            <div class="align-self-center contact-title" style="flex: 1 1 0.5rem">
                <h1 class="title" id="contact-title">Contact</h1>
                <h4 class="subtitle" id="contact-subtitle">This is the way...</h4>
            </div>
            <div class="align-self-center justify-content-center" style="flex: 2 2 3rem">
                <div style="display: flex; flex-direction: row; flex-wrap: wrap;">
                    <h3 class="bold align-self-center mx-auto text-center">dipta004@gmail.com</h3>
                    <div class="vertical-border"></div>
                    <div class="mx-auto my-3">
                        <a href="https://www.linkedin.com/in/diptadwiyantoro/" target="_blank"><img src="/static/iconfinder_square-linkedin_317725.svg" alt="" class="img-fluid contact-img"></a>
                        <a href="https://gitlab.com/dipta004" target="_blank"><img class="img-fluid contact-img" src="/static/iconfinder_144_Gitlab_logo_logos_4373151.svg" alt=""></a>
                        <a href="https://github.com/hsjsjsj009" target="_blank"><img class="img-fluid contact-img" src="/static/iconfinder_mark-github_298822.svg" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <h4 class="text-center"><a href="/lab_4/not_found" class="no-style">For other info. Click Here!</a></h4>
{% endblock %}

lab_5/templates/lab_5/schedule.html
{% extends 'lab_4/base.html' %}

{% block content %}
    <div  id="schedule" class="container part" style="padding-top: 90px; margin-top: 0px; margin-bottom: 0px;">
        <h1 class="text-center bold">My Schedule</h1>
        <div class="row justify-content-center mt-3">
            <div class="col-3">
                <form action="{% url 'lab5:index' %}" method="post">
                    {% csrf_token %}
                    {% for field in forms %}
                    <div class="form-group" style="margin-right: 0; margin-bottom: 10px; font-size: 1rem">
                        <label for="id_{{ field.label.lower }}">{{ field.label }}</label>
                        {{ field.errors }}
                        {{ field }}
                    </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-secondary">Submit</button>
                </form>
            </div>
            <div class="col-5 offset-sm-1">
                {% if length == 0 %}
                    <h3 class="text-center">No Schedule</h3>
                {% endif %}
                <div class="row" style="overflow: auto; height: 28rem">
                {% for i in schedules %}
                    <div class="col-8 mb-3" style="border: #3c3c3c solid;  height: 13rem; border-radius: 10px;">
                        <h4 class="bold">{{ i.title }}</h4>
                        <h5>Location :
                            <span class="semibold">{{ i.location }}</span></h5>
                        <h5 class="bold">{{ i.day }}</h5>
                        <h5>{{ i.date }} {{ i.time }}</h5>
                        <h6 class="bold text-right">{{ i.categories }}</h6>
                        <form action="{% url 'lab5:delete_schedule' id=i.id %}" method="post">
                        {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </div>
                {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <script>
        let monthDOM = document.getElementById("id_date_month");
        let dayDOM = document.getElementById("id_date_day");
        let yearDOM = document.getElementById("id_date_year");
        let dayFormDOM = document.getElementById("id_day");

        let dayList =[
            "Sunday",
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday"
        ]

        let dateDetail = {
            month: monthDOM.value,
            day:dayDOM.value,
            year:yearDOM.value
        }

        let strDate = dateDetail.year+" "+dateDetail.month+"-"+dateDetail.day;
        let date = new Date(strDate);
        dayFormDOM.value = dayList[date.getDay()];

        monthDOM.onchange = (el) => {
            dateDetail.month = el.target.value;
            strDate = dateDetail.year+"-"+dateDetail.month+"-"+dateDetail.day;
            date = new Date(strDate);
            dayFormDOM.value = dayList[date.getDay()];

        }
        dayDOM.onchange = (el) => {
            dateDetail.day = el.target.value;
            strDate = dateDetail.year+"-"+dateDetail.month+"-"+dateDetail.day;
            date = new Date(strDate);
            dayFormDOM.value = dayList[date.getDay()];
        }
        yearDOM.onchange = (el) => {
            dateDetail.year = el.target.value;
            strDate = dateDetail.year+"-"+dateDetail.month+"-"+dateDetail.day;
            date = new Date(strDate);
            dayFormDOM.value = dayList[date.getDay()];
        }


    </script>
{% endblock %}